In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("messy.csv")

In [6]:
df.head(10)

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,11/22/2024,Blender,Home,3,38,Cash on Delivery,Shipped,114.00
1,101,Customer_101,ORD-35783,7/5/2025,Smartphone,Electronics,2,abd,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,12/23/2024,Tennis Racket,Sports,1,389.05,PayPal,Delivered,389.05
3,103,Customer_103,ORD-57811,3/19/2025,Science,Books,5,233.92,PayPal,Processing,1169.60
4,104,Customer_104,ORD-93614,10/20/2025,Biography,Books,1,552.51,Cash on Delivery,Processing,552.51
5,105,Customer_105,ORD-22442,11/20/2024,Tennis Racket,Sports,3,122.06,Cash on Delivery,Cancelled,366.18
6,106,Customer_106,ORD-25885,2/2/2025,Blender,Home,NaN,978.63,Bank Transfer,Processing,NaN
7,107,Customer_107,ORD-89122,1/3/2025,Biography,Books,5,587.68,PayPal,Returned,2938.40
8,108,Customer_108,ORD-64400,10/23/2025,Science,Books,1,600.29,Cash on Delivery,Processing,600.29
9,109,Customer_109,ORD-18512,5/3/2025,Tennis Racket,Sports,5,168.34,Credit Card,Shipped,841.70

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              103 non-null    int64
 1    Customer_Name  103 non-null    str
 2   Order_ID        103 non-null    str
 3   Order_Date      103 non-null    str
 4   Product         103 non-null    str
 5    Category       95 non-null     str
 6   Quantity        98 non-null     str
 7   Price           98 non-null     str
 8   Payment_Method  103 non-null    str
 9   Status          103 non-null    str
 10  Total           89 non-null     float64
dtypes: float64(1), int64(1), str(9)
memory usage: 9.0 KB

In [8]:
df["Price"]

0          38
1         abd
2      389.05
3      233.92
4      552.51
        ...
98     497.01
99     372.28
100    111.36
101    645.26
102    705.42
Name: Price, Length: 103, dtype: str

In [19]:
df["Price"] = pd.to_numeric(df["Price"], errors = "coerce")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              103 non-null    int64
 1    Customer_Name  103 non-null    str
 2   Order_ID        103 non-null    str
 3   Order_Date      103 non-null    str
 4   Product         103 non-null    str
 5    Category       95 non-null     str
 6   Quantity        98 non-null     str
 7   Price           94 non-null     float64
 8   Payment_Method  103 non-null    str
 9   Status          103 non-null    str
 10  Total           89 non-null     float64
dtypes: float64(2), int64(1), str(8)
memory usage: 9.0 KB

In [31]:
df["Quantity"] = pd.to_numeric(df["Quantity"],errors = "coerce").astype("Int64")
df["Quantity"]

0      3
1      2
2      1
3      5
4      1
      ..
98     2
99     5
100    1
101    5
102    2
Name: Quantity, Length: 103, dtype: Int64

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              103 non-null    int64
 1    Customer_Name  103 non-null    str
 2   Order_ID        103 non-null    str
 3   Order_Date      103 non-null    str
 4   Product         103 non-null    str
 5    Category       95 non-null     str
 6   Quantity        97 non-null     float64
 7   Price           94 non-null     float64
 8   Payment_Method  103 non-null    str
 9   Status          103 non-null    str
 10  Total           89 non-null     float64
dtypes: float64(3), int64(1), str(7)
memory usage: 9.0 KB

In [29]:
df.head()

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,11/22/2024,Blender,Home,3.0,38.00,Cash on Delivery,Shipped,114.00
1,101,Customer_101,ORD-35783,7/5/2025,Smartphone,Electronics,2.0,NaN,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,12/23/2024,Tennis Racket,Sports,1.0,389.05,PayPal,Delivered,389.05
3,103,Customer_103,ORD-57811,3/19/2025,Science,Books,5.0,233.92,PayPal,Processing,1169.60
4,104,Customer_104,ORD-93614,10/20/2025,Biography,Books,1.0,552.51,Cash on Delivery,Processing,552.51

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              103 non-null    int64
 1    Customer_Name  103 non-null    str
 2   Order_ID        103 non-null    str
 3   Order_Date      103 non-null    str
 4   Product         103 non-null    str
 5    Category       95 non-null     str
 6   Quantity        97 non-null     Int64
 7   Price           94 non-null     float64
 8   Payment_Method  103 non-null    str
 9   Status          103 non-null    str
 10  Total           89 non-null     float64
dtypes: Int64(1), float64(2), int64(1), str(7)
memory usage: 9.1 KB

In [33]:
df.to_csv("Clean.csv",index =False)