In [2]:
import pandas as pd 
import numpy as np

In [3]:
df = pd.read_csv("sales.csv")

In [4]:
## check data type for each of the followning column

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1004 entries, 0 to 1003
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    1004 non-null   int64
 1   customer_id       1001 non-null   float64
 2   customer_name     951 non-null    str
 3   email             1004 non-null   str
 4   purchase_date     1004 non-null   str
 5   product_id        1004 non-null   int64
 6   category          837 non-null    str
 7   price             946 non-null    float64
 8   quantity          1004 non-null   int64
 9   total_amount      757 non-null    float64
 10  payment_method    866 non-null    str
 11  delivery_status   873 non-null    str
 12  customer_address  950 non-null    str
dtypes: float64(3), int64(3), str(7)
memory usage: 102.1 KB

In [6]:
# Now convert the columns into relvent data type
df = df.convert_dtypes()

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1004 entries, 0 to 1003
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    1004 non-null   Int64
 1   customer_id       1001 non-null   Int64
 2   customer_name     951 non-null    string
 3   email             1004 non-null   string
 4   purchase_date     1004 non-null   string
 5   product_id        1004 non-null   Int64
 6   category          837 non-null    string
 7   price             946 non-null    Float64
 8   quantity          1004 non-null   Int64
 9   total_amount      757 non-null    Float64
 10  payment_method    866 non-null    string
 11  delivery_status   873 non-null    string
 12  customer_address  950 non-null    string
dtypes: Float64(2), Int64(4), string(7)
memory usage: 108.0 KB

In [8]:
df = df.dropna(subset=['customer_id','price'],how = "all")
df.isnull().sum()

transaction_id        0
customer_id           3
customer_name        53
email                 0
purchase_date         0
product_id            0
category            167
price                58
quantity              0
total_amount        247
payment_method      138
delivery_status     131
customer_address     54
dtype: int64

In [9]:
## how to remove null values in the data frame
df.head()

,transaction_id,customer_id,customer_name,email,purchase_date,product_id,category,price,quantity,total_amount,payment_method,delivery_status,customer_address
0,1001,102,Amy Wells,caroladams@gmail.com,24/01/2024,1023,Clothing,4210.71,-1,-4210.71,creditcard,Pending,"5769 Tracy Lane\nPort Amy, AZ 35865"
1,1002,435,Joshua Lopez,brownbenjamin,05/09/2023,1029,Electronics,3298.49,-3,-9895.47,Debit Card,Delivered,"70936 Rangel Falls\nWellshaven, AK 75186"
2,1003,348,Richard Alvarado,rose47@hotmail.com,09/07/2024,1078,Books,2387.86,6,14327.16,CC,Returned,"724 Aaron Villages\nPatriciachester, VA 64309"
3,1004,270,Nichole Nelson,sgibbs@reeves.org,28/07/2023,1090,Clothing,3780.65,2,7561.3,creditcard,Shipped,"4983 James Plains\nRoachland, NJ 41398"
4,1005,106,Debbie Baker,vvargas@gmail.com,10/09/2023,1051,Toys,562.62,5,<NA>,<NA>,Shipped,"03845 Bryan Branch Suite 738\nNew Joelside, ID..."

In [10]:
df = df.dropna(subset=["customer_id", "price"])

In [11]:
df["payment_method"]= df["payment_method"].fillna("unknown")

In [12]:
df["category"] = df["category"].fillna("unknown")

In [13]:
df["category"]

0             Clothing
1          Electronics
2                Books
3             Clothing
4                 Toys
             ...
999            unknown
1000          Clothing
1001    Home & Kitchen
1002           unknown
1003           unknown
Name: category, Length: 943, dtype: string

In [14]:
df["payment_method"]

0          creditcard
1          Debit Card
2                  CC
3          creditcard
4             unknown
            ...
999           unknown
1000       creditcard
1001           PayPal
1002    Bank Transfer
1003       Debit Card
Name: payment_method, Length: 943, dtype: string

In [15]:
cp = df[["customer_id","price"]]
cp.isnull().sum()

customer_id    0
price          0
dtype: int64

In [16]:
paycat =  df[["category","payment_method"]]
paycat.isnull().sum()

category          0
payment_method    0
dtype: int64

In [17]:
df.head()

,transaction_id,customer_id,customer_name,email,purchase_date,product_id,category,price,quantity,total_amount,payment_method,delivery_status,customer_address
0,1001,102,Amy Wells,caroladams@gmail.com,24/01/2024,1023,Clothing,4210.71,-1,-4210.71,creditcard,Pending,"5769 Tracy Lane\nPort Amy, AZ 35865"
1,1002,435,Joshua Lopez,brownbenjamin,05/09/2023,1029,Electronics,3298.49,-3,-9895.47,Debit Card,Delivered,"70936 Rangel Falls\nWellshaven, AK 75186"
2,1003,348,Richard Alvarado,rose47@hotmail.com,09/07/2024,1078,Books,2387.86,6,14327.16,CC,Returned,"724 Aaron Villages\nPatriciachester, VA 64309"
3,1004,270,Nichole Nelson,sgibbs@reeves.org,28/07/2023,1090,Clothing,3780.65,2,7561.3,creditcard,Shipped,"4983 James Plains\nRoachland, NJ 41398"
4,1005,106,Debbie Baker,vvargas@gmail.com,10/09/2023,1051,Toys,562.62,5,<NA>,unknown,Shipped,"03845 Bryan Branch Suite 738\nNew Joelside, ID..."

In [18]:
df["isnull"] = df["quantity"] < 0

In [19]:
df["quantity"] = df["quantity"].abs()

In [20]:
df["quantity"]

0       1
1       3
2       6
3       2
4       5
       ..
999     8
1000    1
1001    4
1002    6
1003    1
Name: quantity, Length: 943, dtype: Int64

In [21]:
df["total_amount"] = df["total_amount"].abs()

In [22]:
df["total_amount"]

0        4210.71
1        9895.47
2       14327.16
3         7561.3
4           <NA>
          ...
999      25107.6
1000     4840.26
1001     2751.72
1002    11581.08
1003     4210.44
Name: total_amount, Length: 943, dtype: Float64

In [23]:
df.head(2)

,transaction_id,customer_id,customer_name,email,purchase_date,product_id,category,price,quantity,total_amount,payment_method,delivery_status,customer_address,isnull
0,1001,102,Amy Wells,caroladams@gmail.com,24/01/2024,1023,Clothing,4210.71,1,4210.71,creditcard,Pending,"5769 Tracy Lane\nPort Amy, AZ 35865",True
1,1002,435,Joshua Lopez,brownbenjamin,05/09/2023,1029,Electronics,3298.49,3,9895.47,Debit Card,Delivered,"70936 Rangel Falls\nWellshaven, AK 75186",True

In [24]:
df["total_amount"].isnull().sum()

np.int64(189)

In [25]:
df["total_amount"] = df["total_amount"].fillna(df["price"] * df["quantity"])

In [26]:
df["total_amount"].isnull().sum()

np.int64(0)

In [27]:
df["missing_total"] = df["total_amount"].isna()
df["missing_total"]

0       False
1       False
2       False
3       False
4       False
        ...
999     False
1000    False
1001    False
1002    False
1003    False
Name: missing_total, Length: 943, dtype: bool

In [31]:
df.to_csv("cleaned.csv",index = False)